spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle:1521:ORCLCDB
    username: system
    password: nareshit

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true